In [1]:
import numpy as np
import random

In [8]:
#Initialize values
X = np.array([[3], [5], [7]])
Y = np.array([[1]])

W1 = np.random.randn(4, 3) * .01
b1 = np.zeros((4, 1))

W2 = np.random.randn(1, 4) * .01
b2 = np.zeros((1,1))

print("X:", X)
print("Y:", Y)
print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:", b2)

X: [[3]
 [5]
 [7]]
Y: [[1]]
W1:
 [[-0.0238252  -0.00145192  0.02906031]
 [-0.01620661  0.0126301  -0.0043321 ]
 [ 0.00673367 -0.00266045  0.01863142]
 [ 0.00314836 -0.00410666 -0.01961408]]
b1:
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
W2:
 [[ 0.00588104  0.00417777  0.00675327 -0.00719804]]
b2: [[ 0.]]


In [11]:
#Forward Propagation
Z1 = np.dot(W1, X) + b1 # 4x3 . 3x1 = 4x1
A1 = np.tanh(Z1) # 4x1
Z2 = np.dot(W2, A1) + b2 # 1x1
A2 = 1 / (1 + np.exp(-Z2)) # sigmoid activation function - 1x1

print("Z1:\n", Z1)
print("A1:\n", A1)
print("Z2:", Z2)
print("A2:", A2)

Z1:
 [[ 0.12468696]
 [-0.01579403]
 [ 0.13731876]
 [-0.14838678]]
A1:
 [[ 0.12404479]
 [-0.01579271]
 [ 0.13646211]
 [-0.14730719]]
Z2: [[ 0.00264542]]
A2: [[ 0.50066136]]


In [14]:
m = X.shape[1]

cost = (-1/m) * np.sum(np.multiply(np.log(A2), Y) - np.multiply(np.log(1-A2), 1-Y))
print("m:", m)
print("cost:", cost)

m: 1
cost: 0.691825343897


In [18]:
# Back Propagation

dZ2 = A2 - Y
dW2 = (1/m) * np.dot(dZ2, A1.T)
db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)
dZ1 = np.dot(W2.T, dZ2) * (1 - np.power(A1, 2))
dW1 = (1/m) * (np.dot(dZ1, X.T))
db1 = (1/m) * np.sum(dZ1)

print("dZ2:", dZ2)
print("dW2:", dW2)
print("db2:", db2)
print("dZ1:\n", dZ1)
print("dW1:\n", dW1)
print("db1:\n", db1)

dZ2: [[-0.49933864]]
dW2: [[-0.06194036  0.00788591 -0.06814081  0.07355617]]
db2: [[-0.49933864]]
dZ1:
 [[-0.00289145]
 [-0.0020856 ]
 [-0.00330937]
 [ 0.00351627]]
dW1:
 [[-0.00867434 -0.01445723 -0.02024012]
 [-0.00625681 -0.01042801 -0.01459922]
 [-0.00992812 -0.01654686 -0.02316561]
 [ 0.0105488   0.01758133  0.02461386]]
db1:
 -0.00477015518275


In [21]:
# update parameters
alpha = .1 #learning rate
W1 = W1 - alpha * dW1
b1 = b1 - alpha * db1
W2 = W2 - alpha * dW2
b2 = b2 - alpha * db2

print("W1:\n", W1)
print("b1:\n", b1)
print("W2:", W2)
print("b2:", b2)

W1:
 [[ -2.12228961e-02   2.88525093e-03   3.51323427e-02]
 [ -1.43295678e-02   1.57585001e-02   4.76681609e-05]
 [  9.71210770e-03   2.30361336e-03   2.55811070e-02]
 [ -1.62746255e-05  -9.38105463e-03  -2.69982427e-02]]
b1:
 [[ 0.00143105]
 [ 0.00143105]
 [ 0.00143105]
 [ 0.00143105]]
W2: [[ 0.02446315  0.001812    0.02719551 -0.02926489]]
b2: [[ 0.14980159]]
