In [2]:
import numpy as np
import math
import time

In [3]:
# e function, only can handle on exponent
math.e**2

7.3890560989306495

In [4]:
# np.array([[]])
# use double [[]] to default to 2 dim array, otherwise will default to rank 1 array

vector = np.array([[1,2,3,4,5]])
print(vector)
print(vector.shape)

[[1 2 3 4 5]]
(1, 5)


In [41]:
# np.exp() applies exponential operation e^x to an array or matrix 

a = np.array([1,2,3,4,5])
y = np.array([[6,7,8,9,10], [6, 7, 8, 9, 10]])

print("np.exp(a)")
print(np.exp(a), "\n")
print("np.exp(y)")
print(np.exp(y))

np.exp(a)
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591 ] 

np.exp(y)
[[   403.42879349   1096.63315843   2980.95798704   8103.08392758
   22026.46579481]
 [   403.42879349   1096.63315843   2980.95798704   8103.08392758
   22026.46579481]]


In [37]:
# np.zeros() / np.ones() 
# specifies a vector or matrix of zeros or ones, specify shape to avoid rank 1 arrays

# rank 1 array, has shape of (x, ), can cause unwanted behavior
rank1 = np.zeros(7)
print(rank1)
print("rank 1 array shape:", rank1.shape, "\n")

vector = np.ones((6,1))
print(vector)
print("vector shape:", vector.shape, "\n")

matrix = np.zeros((3, 5))
print(matrix)
print("matrix shape:", matrix.shape, "\n")

[ 0.  0.  0.  0.  0.  0.  0.]
rank 1 array shape: (7,) 

[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
vector shape: (6, 1) 

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
matrix shape: (3, 5) 



In [50]:
# np.random.rand() /np.random.randn() generates random numbers of a given distribution for a specified shape

# normal distribution between 0-1
rand1 = np.random.rand(2,4)
print(rand1, ", shape:", rand1.shape,"\n")

# normal distribution centered around 0
rand2 = np.random.randn(4,4)
print(rand2, ", shape:", rand2.shape)




[[ 0.32353601  0.96435099  0.11422496  0.19594817]
 [ 0.16267106  0.84943052  0.51214856  0.23034307]] , shape: (2, 4) 

[[ 1.78841329  0.11274844 -0.19195476 -0.85443202]
 [-0.57391947  1.58584265  0.0926365  -0.51598246]
 [-0.34384272  0.78828842  0.68338206 -0.29420242]
 [-1.1491433  -1.87138553  0.65362135 -0.19999711]] , shape: (4, 4)


In [20]:
# np.linalg.norm()
# normalizes each row of the matrix x (to have unit length)
x = np.array([[
    [0, 3, 4],
    [1, 6, 4]]])
x_norm = np.linalg.norm(x, ord=2, axis=1, keepdims=True)

normalized = x / x_norm
print(normalized)

[[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


In [39]:
#Transposing matrices/vectors with .T

x = np.array([[1,2,3,4,5], [1, 2, 3, 4, 5]])
y = np.array([[6,7,8,9,10], [6, 7, 8, 9, 10]])

print("np.dot(x.T, y)")
print(np.dot(x.T, y), "\n")	# 5x2 x 2x5 = 5x5
print("np.dot(x, y.T)")
print(np.dot(x, y.T))	# 2x5 x 5x2 = 2x2

np.dot(x.T, y)
[[ 12  14  16  18  20]
 [ 24  28  32  36  40]
 [ 36  42  48  54  60]
 [ 48  56  64  72  80]
 [ 60  70  80  90 100]] 

np.dot(x, y.T)
[[130 130]
 [130 130]]


In [21]:
# softmax
# converts vector to a value between 0,1

x = np.array([
[9, 2, 5, 0, 0],
[7, 5, 0, 0 ,0]])

x_exp = np.exp(x)
print("x_exp: ", np.shape(x_exp))

x_sum = np.sum(x_exp, axis = 1, keepdims = True)
print("x_sum: ", np.shape(x_sum))

# Compute softmax(x) by dividing x_exp by x_sum. It should automatically use numpy broadcasting.
s = x_exp / x_sum
print("s: ", np.shape(s))
    
    


x_exp:  (2, 5)
x_sum:  (2, 1)
s:  (2, 5)


In [22]:
# np.sum()

In [ ]:
# broadcasting

In [57]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print("\n")
### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.0ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.0ms


elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0ms
gdot = [ 19.79874162  26.08104826  28.97845684]
 ----- Computation time = 0.0ms
