In [1]:
import numpy as np
import math
import random
import matplotlib.pyplot as plt
from deep_nn_utilities import *

In [2]:
X = np.array([[2, 4, 6], [6, 8, 10], [10, 20, 30]]).T
Y = np.ones((1, 3))
W = np.random.randn(1, 3) * .01
print(W)
b = np.zeros((1, 1,))
# Y = np.array([np.average(X, axis=0)])
# print("X:\n", X)
# print("Y:\n", Y)

[[-0.00151044 -0.00702516  0.00377422]]


In [3]:
# parameters = initialize_parameters([5, 4, 3])
Z, cache = linear_forward(X, W, b)
print(Z, cache)

[[-0.00847622 -0.02752176 -0.04238112]] (array([[ 2,  6, 10],
       [ 4,  8, 20],
       [ 6, 10, 30]]), array([[-0.00151044, -0.00702516,  0.00377422]]), array([[ 0.]]))


In [4]:
layer_dims = [3, 5 , 4, 3, 1]

In [5]:
def L_layer_model(X, Y, layer_dims, learning_rate = .0075, num_iterations = 3000, print_cost = False):
    np.random.seed(1)
    costs = []
    
    parameters = initialize_parameters(layer_dims)
    
    for i in range(0, num_iterations):
        AL, caches = L_model_forward(X, parameters)
        
        cost = compute_cost(AL, Y)
        
        grads = L_model_backward(AL, Y, caches)
        
        parameters = update_parameters(parameters, grads, learning_rate)
        
        # Print the cost every 100 training example
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
        if print_cost and i % 100 == 0:
            costs.append(cost)
            
    # plot the cost
#     plt.plot(np.squeeze(costs))
#     plt.ylabel('cost')
#     plt.xlabel('iterations (per tens)')
#     plt.title("Learning rate =" + str(learning_rate))
#     plt.show()
    
    return parameters

In [6]:
parameters = L_layer_model(X, Y, layer_dims, .0075, 4000, False)
p = predict(X, Y, parameters)
print(p)

Accuracy: 1.0
[[ 1.  1.  1.]]
